apiVersion: v1
kind: Pod
metadata:
  name: workload-identity-test
  namespace: {{ .Chart.Namespace }}
spec:
  containers:
  - image: google/cloud-sdk:slim
    name: workload-identity-test
    command: ["sleep","infinity"]
  serviceAccountName: {{ .Chart.Name }}-serviceaccount